---
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy

  kucoin-proxy:
    image: stash86/kucoin-proxy:latest
    restart: unless-stopped
    command: -verbose 1
    container_name: github.com/stash86/kucoin-proxy-proxy
